### ISSUE TITLE
AttributeError: install_layout when installing sbws using python 3.4.5

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#203] opened 2018-06-19 12:07 UTC
Full trace:

```
path$ python setup.py install
/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running install
Traceback (most recent call last):
  File "setup.py", line 85, in <module>
    'doc': ['sphinx', 'recommonmark'],
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/path/.virtualenvs/sbws345env/lib/python3.4/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/path/.virtualenvs/sbws345env/lib/python3.4/site-packages/setuptools/command/install.py", line 103, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/path/.virtualenvs/sbws345env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 283, in finalize_options
    'install_lib', ('install_dir', 'install_dir')
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/path/.virtualenvs/sbws345env/lib/python3.4/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/path/.pyenv/versions/3.4.5/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout
```

**Comment by juga0** [comment] 2018-06-19 12:08
I think it's not worth to to fix these issues and we could just remove support for python 3.4.
Also commented in https://github.com/pastly/simple-bw-scanner/issues/194#issuecomment-398008386

**Comment by pastly** [comment] 2018-06-19 12:47
I think the issue is that you're calling `python setup.py install` instead of `pip install .`

[This](https://stackoverflow.com/questions/8295644/pypi-userwarning-unknown-distribution-option-install-requires#10686196) was one of the first DDG search results and what I'm basing this comment on.

**Comment by juga0** [comment] 2018-06-19 13:00
That would be for the warning ``install_requires``, but not for the ``AttributeError``. 
I get same error calling ``pip install .``.

**Comment by juga0** [comment] 2018-06-25 09:45
I think this happened because while using ``pyenv``, the ``virtualenv`` got created with system libraries. Running ``pip install -U setuptools`` solved the issue.
Creating the ``virtualenv`` with ``pyenv-virtualenv`` didn't have this problem. However ``pip install -e .`` does not install the required libraries, i guess because it ignores ``install_requires``.
It seems to me that to properly support ``3.4.5`` we would need to duplicate ``setup`` and use ``distutils`` instead of ``setuptools`` when python version is minor than ``3.5``.
Do we want to still support python ``3.4``?.
If yes, i'd wait to see if this error does not happen when installing ``sbws`` as a system package with system libraries.

**Comment by juga0** [comment] 2018-06-25 09:45
What commented above also happens with ``python setup.py install``

**Comment by juga0** [comment] 2018-07-03 11:34
I have created again two different ``pyenv-virtualenvs`` with the proper libraries (``libssl1.0-dev`` in Debian, instead of ``libssl-dev`` which is newer) and didn't run into this error.
Probably running python 3.4.5 from system packages won't run into this error, so i think this can be closed and re-open if it happens again in other environment.

**Comment by pastly** [comment] 2018-07-03 13:19
Thanks for looking into this @juga0. Closing as you suggest.

**Closed by pastly** 2018-07-03 13:19 UTC
Labels: bug
